[theme]
# Primary accent color for interactive elements.
primaryColor = "#FF0E41"

# Background color for the main content area.
backgroundColor = "#145287"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#71BEDC"

# Color used for almost all text.
textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
